
# Note that samples need to paired positionally to be analyzed correctly
# ex. test1_long and test1_short belong to the same sample type
samples:
  long:
    - 'test1_long'
    - 'test2_long'
    - 'test3_long'
    - 'test4_long'
    - 'test5_long'
    - 'test6_long'
  short:
    - 'test1_short'
    - 'test2_short'
    - 'test3_short'
    - 'test4_short'
    - 'test5_short'
    - 'test6_short'
  exp:
    'experiment_info'

genome:
  gtf:
    "resources/genome/Homo_sapiens.GRCh38.106.gtf"
  fa:
    "resources/genome/Homo_sapiens.GRCh38.dna.primary_assembly.fa"

qc_list:
  - 'test1_long'
  - 'test2_long'
  - 'test3_long'
  - 'test4_long'
  - 'test1_short_1'
  - 'test1_short_2'
  - 'test2_short_1'
  - 'test2_short_2'
  - 'test3_short_1'
  - 'test3_short_2'
  - 'test4_short_1'
  - 'test4_short_2'
  - 'test5_short_1'
  - 'test5_short_2'
  - 'test6_short_1'
  - 'test6_short_2'

STAR_index:
  "results/aligned/STAR_index"



